.TH opx-interface-beacon "1" "2018-11-20" OPX "OPX utilities"
.SH NAME
opx-interface-beacon \- Turn front-panel port beacon LED on or off
.SH SYNOPSIS
.SY opx-interface-beacon
.OP "\fB\-h\fR | \fB\-\-help\fR"
.I port
.RB { on \ | \ off }
.YS
.SH DESCRIPTION
This command turns on or off the beacon LED for the given front-panel port.
.SH OPTIONS
.TP
\-h, \-\-help
Print help text.
.TP
.I port
The front-panel port whose beacon LED will be turned on or off.
.SH EXIT STATUS
If there is a syntax error in the given arguments, the exit status shall be 2.
.br
If the command fails to set the beacon LED, the exit status shall be 1.
.br
Otherwise, the exit status is 0.
.SH EXAMPLE
.nf
.eo
$ opx-interface-beacon e101-001-0 on
.ec
.fi
.SH REPORTING BUGS
To report any OPX software bugs, please refer to https://github.com/open-switch/opx-docs/wiki/Report-bugs.
.SH COPYRIGHT
Copyright \(co 2018 Dell Inc. and its subsidiaries. All Rights Reserved.
.SH SEE ALSO
opx-chassis-beacon(1)
