.TH opx-show-interface-stats "1" "2018-11-20" OPX "OPX utilities"
.SH NAME
opx-show-interface-stats \- Display Ethernet interface statistics counters
.SH SYNOPSIS
.SY opx-show-interface-stats
.OP \-h
.OP \-\-help
.OP \-\-port port-list
.OP \-\-nonzero
.YS
.SH DESCRIPTION
This command prints the statistics for the given front-panel Ethernet interfaces.
.SH OPTIONS
.TP
\-h, \-\-help
Print help text.
.TP
--port \fIport-list\fR
Specify front panel Ethernet interface(s) to print.  A
.I port-list
is a comma-separated list of 1 one more ranges.  Each range is either a single interface, or a pair of interfaces of the form \fIfrom\fR..\fIto\fR, which specifies all interfaces from \fIfrom\fR to \fIto\fR inclusive.
Examples are:
.sp 1
e101-001-0 \- Expands to e101-001-0
.sp 1
e101-001-0,e101-010-0 \- Expands to e101-001-0,e101-010-0
.sp 1
e101-001-0,e101-004-0..e101-006-0 \- Expands to e101-001-0,e101-004-0,e101-005-0,e101-006-0
.sp 1
If the port list is not specified, all Ethernet front-panel ports are shown.
.TP
--nonzero
Show only those counters that are not zero.
.SH STATISTICS COUNTERS
.TP
Alignment errors
Number of inbound Ethernet frames that are not an integral number of octets in length and do not pass the FCS check.
.TP
Carrier sense errors
Number of times that the carrier sense condition was lost or never asserted when attempting to transmit a frame.
.TP
Deferred transmissions
Number of Ethernet frames for which the first transmission attempt is delayed because the medium is busy.
.TP
ECN marked packets
Number of packets marked with explicit congestion notification (ECN).
.TP
Ethernet broadcast packets
Number of Ethernet broadcast frames.
.TP
Ethernet collisions
Number of Ethernet media access collisions.
.TP
Ethernet CRC align errors

.TP
Ethernet drop events

.TP
Ethernet fragments

.TP
Ethernet in packets (64 octets)
Number of inbound Ethernet frames exactly 64 octets in length.
.TP
Ethernet in packets (65 to 127 octets)
Number of inbound Ethernet frames between 65 and 127 octets in length (inclusive).
.TP
Ethernet in packets (128 to 255 octets)
Number of inbound Ethernet frames between 128 and 255 octets in length (inclusive).
.TP
Ethernet in packets (256 to 511 octets)
Number of inbound Ethernet frames between 256 and 511 octets in length (inclusive).
.TP
Ethernet in packets (512 to 1023 octets)
Number of inbound Ethernet frames between 512 and 1023 octets in length (inclusive).
.TP
Ethernet in packets (1024 to 1518 octets)
Number of inbound Ethernet frames between 1024 and 1518 octets in length (inclusive).
.TP
Ethernet in packets (1519 to 2047 octets)
Number of inbound Ethernet frames between 1519 and 2047 octets in length (inclusive).
.TP
Ethernet in packets (2048 to 4095 octets)
Number of inbound Ethernet frames between 2048 and 4095 octets in length (inclusive).
.TP
Ethernet in packets (4096 to 9216 octets)
Number of inbound Ethernet frames between 4096 and 9216 octets in length (inclusive).
.TP
Ethernet jabbers

.TP
Ethernet multicast packets
Number of Ethernet multicast frames.
.TP
Ethernet octets

.TP
Ethernet out packets (64 octets)
Number of transmitted Ethernet frames exactly 64 octets in length.
.TP
Ethernet out packets (65 to 127 octets)
Number of transmitted Ethernet frames between 65 and 127 octets in length.
.TP
Ethernet out packets (128 to 255 octets)
Number of transmitted Ethernet frames between 128 and 255 octets in length.
.TP
Ethernet out packets (256 to 511 octets)
Number of transmitted Ethernet frames between 256 and 511 octets in length.
.TP
Ethernet out packets (512 to 1023 octets)
Number of transmitted Ethernet frames between 512 and 1023 octets in length.
.TP
Ethernet out packets (1024 to 1518 octets)
Number of transmitted Ethernet frames between 1024 and 1518 octets in length.
.TP
Ethernet out packets (1519 to 2047 octets)
Number of transmitted Ethernet frames between 1519 and 2047 octets in length.
.TP
Ethernet out packets (2048 to 4095 octets)
Number of transmitted Ethernet frames between 2048 and 4095 octets in length.
.TP
Ethernet out packets (4096 to 9216 octets)
Number of transmitted Ethernet frames between 4096 and 9216 octets in length.
.TP
Ethernet oversize packets

.TP
Ethernet packets

.TP
Ethernet rx no errors

.TP
Ethernet rx oversize packets

.TP
Ethernet tx no errors

.TP
Ethernet tx oversize packets

.TP
Ethernet undersize packets

.TP
Excessive collisions
Number of outbound Ethernet frames for which transmission fails due to excessive collisions.
.TP
FCS errors
Number of inbound Ethernet frames that are an integral number of octets in length but do not pass the FCS check. 
.TP
Frame too long
Number of inbound Ethernet frames that exceed the maximum permitted frame size.
.TP
Green discard dropped packets

.TP
In broadcast packets
The number of inbound Ethernet frames that were addressed to a broadcast address.
.TP
In discards
The number of inbound frames that were chosen to be discarded even though no errors had been detected to prevent their being deliverable to a higher-layer protocol.  One possible reason for discarding such a frame could be to free up buffer space. 
.TP
In errors
The number of inbound Ethernet frames that contained errors preventing them from being deliverable to a higher-layer protocol.
.TP
In multicast packets
The number of packets, delivered by this sub-layer to a higher (sub-)layer, that were addressed to a multicast address at this sub-layer.  For a MAC-layer protocol, this includes both Group and Functional addresses. 
.TP
In octets
The total number of octets inbound on the interface, including framing characters.
.TP
In unicast packets
The number of packets, delivered by this sub-layer to a higher (sub-)layer, that were not addressed to a multicast or broadcast address at this sub-layer.
.TP
In unknown opcodes
Number of inbound Ethernet MAC Control frames that contain an opcode that is not supported.
.TP
In unknown protos
For packet-oriented interfaces, the number of packets received via the interface that were discarded because of an unknown or unsupported protocol.  For character-oriented or fixed-length interfaces that support protocol multiplexing, the number of transmission units received via the interface that were discarded because of an unknown or unsupported protocol. For any interface that does not support protocol multiplexing, this counter is not present. 
.TP
Internal MAC receive errors
Number of inbound Ethernet frames for which reception fails due to an internal MAC sublayer receive error.
.TP
Internal MAC transmit errors
Number of outbound Ethernet frames for which transmission fails due to an internal MAC sublayer transmit error.
.TP
IP in discards

.TP
IP in forwarded datagrams

.TP
IP in header errors

.TP
IP in receives

.TP
IPv6 in address errors

.TP
IPv6 in discards

.TP
IPv6 in header errors

.TP
IPv6 in multicast packets

.TP
IPv6 in receives

.TP
IPv6 out discards

.TP
IPv6 out forwarded datagrams

.TP
IPv6 out multicast packets

.TP
Late collisions
Number of times that a collision is detected later than one slotTime into the transmission of a frame.
.TP
Multiple colision frames
Number of inbound Ethernet frames that are involved in more than one collision and are subsequently transmitted successfully.
.TP
Out broadcast packets
The total number of packets that higher-level protocols requested be transmitted, and that were addressed to a broadcast address at this sub-layer, including those that were discarded or not sent. 
.TP
Out discards
The number of outbound packets that were chosen to be discarded even though no errors had been detected to prevent their being transmitted.  One possible reason for discarding such a packet could be to free up buffer space. 
.TP
Out errors
For packet-oriented interfaces, the number of outbound packets that could not be transmitted because of errors. For character-oriented or fixed-length interfaces, the number of outbound transmission units that could not be transmitted because of errors. 
.TP
Out multicast packets
The total number of packets that higher-level protocols requested be transmitted, and that were addressed to a multicast address at this sub-layer, including those that were discarded or not sent.  For a MAC-layer protocol, this includes both Group and Functional addresses. 
.TP
Out octets
The total number of octets transmitted out of the interface, including framing characters. 
.TP
Out queue length
Transmit queue length.
.TP
Out unicast packets
The total number of packets that higher-level protocols requested be transmitted, and that were not addressed to a multicast or broadcast address at this sub-layer, including those that were discarded or not sent. 
.TP
Pause rx packets

.TP
Pause tx packets

.TP
PFC 0 rx packets

.TP
PFC 0 tx packets

.TP
PFC 1 rx packets

.TP
PFC 1 tx packets

.TP
PFC 2 rx packets

.TP
PFC 2 tx packets

.TP
PFC 3 rx packets

.TP
PFC 3 tx packets

.TP
PFC 4 rx packets

.TP
PFC 4 tx packets

.TP
PFC 5 rx packets

.TP
PFC 5 tx packets

.TP
PFC 6 rx packets

.TP
PFC 6 tx packets

.TP
PFC 7 rx packets

.TP
PFC 7 tx packets

.TP
RED discard dropped packets

.TP
Rx lpi count

.TP
Rx lpi duration

.TP
Single collision frames
Number of inbound Ethernet frames that are involved in a single collision, and are subsequently transmitted successfully.
.TP
SQE test errors
Number of times that the SQE TEST ERROR is received.
.TP
Symbol errors
Number of various carrier events on an interface depending on its speed and type, eg. 'invalid data symbol' (100 Mb/s speed), 'Data reception error'(1000 Mb/s speed and half-duplex), 'Carrier extend error'(1000 Mb/s speed and full-duplex).   For more details refer RFC 3635 Section 4.
.TP
Time stamp

.TP
Tx lpi count

.TP
Tx lpi duration

.TP
Yellow discard dropped packets

.SH EXIT STATUS
If an invalid port list is specified, the exit status shall be 1.
.br
If there is a syntax error in the given arguments, the exit status shall be 2.
.br
Otherwise, the exit status is 0.
.SH EXAMPLE
.nf
.eo
$ opx-show-interface-stats --port e101-001-0
Port e101-001-0
	Alignment errors:                           0
	Carrier sense errors:                       0
	Deferred transmissions:                     0
	ECN marked packets:                         0
	Ethernet broadcast packets:                 0
	Ethernet collisions:                        0
	Ethernet CRC align errors:                  0
	Ethernet drop events:                       0
	Ethernet fragments:                         0
	Ethernet in packets (64 octets):            0
	Ethernet in packets (65 to 127 octets):     330704
	Ethernet in packets (128 to 255 octets):    82857
	Ethernet in packets (256 to 511 octets):    0
	Ethernet in packets (512 to 1023 octets):   0
	Ethernet in packets (1024 to 1518 octets):  0
	Ethernet in packets (1519 to 2047 octets):  0
	Ethernet in packets (2048 to 4095 octets):  0
	Ethernet in packets (4096 to 9216 octets):  0
	Ethernet jabbers:                           0
	Ethernet multicast packets:                 662274
	Ethernet octets:                            94138869
	Ethernet out packets (64 octets):           0
	Ethernet out packets (65 to 127 octets):    316757
	Ethernet out packets (128 to 255 octets):   82850
	Ethernet out packets (256 to 511 octets):   0
	Ethernet out packets (512 to 1023 octets):  0
	Ethernet out packets (1024 to 1518 octets): 0
	Ethernet out packets (1519 to 2047 octets): 0
	Ethernet out packets (2048 to 4095 octets): 0
	Ethernet out packets (4096 to 9216 octets): 0
	Ethernet oversize packets:                  0
	Ethernet packets:                           813168
	Ethernet rx no errors:                      413561
	Ethernet rx oversize packets:               0
	Etherent tx no errors:                      399607
	Ethernet tx oversize packets:               0
	Ethernet undersize packets:                 0
	Excessive collisions:                       0
	FCS errors:                                 0
	Frame too long:                             0
	Green discard dropped packets:              0
	In broadcast packets:                       0
	In discards:                                0
	In errors:                                  0
	In multicast packets:                       330986
	In octets:                                  47697992
	In unicast packets:                         82575
	In unknown opcodes:                         0
	In unknown protocols:                       0
	Internal MAC receive errors:                0
	Internal MAC transmit errors:               0
	IP in discards:                             0
	IP in forwarded datagrams:                  0
	IP in header errors:                        0
	IP in receives:                             13
	IPv6 in address errors:                     0
	IPv6 in discards:                           0
	IPv6 in header errors:                      0
	IPv6 in multicast packets:                  0
	IPv6 in receives:                           39
	IPv6 out discards:                          0
	IPv6 out forwarded datagrams:               0
	IPv6 out multicast packets:                 0
	Late collisions:                            0
	Multiple collision frames:                  0
	Out broadcast packets:                      0
	Out discards:                               0
	Out errors:                                 0
	Out multicast packets:                      331288
	Out octets:                                 46440877
	Out queue length:                           0
	Out unicast packets:                        68319
	Pause rx packets:                           0
	Pause tx packets:                           0
	PFC 0 rx packets:                           0
	PFC 0 tx packets:                           0
	PFC 1 rx packets:                           0
	PFC 1 tx packets:                           0
	PFC 2 rx packets:                           0
	PFC 2 tx packets:                           0
	PFC 3 rx packets:                           0
	PFC 3 tx packets:                           0
	PFC 4 rx packets:                           0
	PFC 4 tx packets:                           0
	PFC 5 rx packets:                           0
	PFC 5 tx packets:                           0
	PFC 6 rx packets:                           0
	PFC 6 tx packets:                           0
	PFC 7 rx packets:                           0
	PFC 7 tx packets:                           0
	RED discard dropped packets:                0
	Rx lpi count:                               0
	Rx lpi duration:                            0
	Single collision frames:                    0
	SQE test errors:                            0
	Symbol errors:                              0
	Time stamp:                                 4049502
	Tx lpi count:                               0
	Tx lpi duration:                            0
	Yellow discard dropped packets:             0
.ec
.fi
.SH REPORTING BUGS
To report any OPX software bugs, please refer to https://github.com/open-switch/opx-docs/wiki/Report-bugs.
.SH COPYRIGHT
Copyright \(co 2018 Dell Inc. and its subsidiaries. All Rights Reserved.
