.TH opx-config-route "1" "2018-12-10" OPX "OPX utilities"
.SH NAME
opx-show-vrf \- Show static route
.SH SYNOPSIS
.SY opx-config-route
.OP \-h
.OP \-\-help
.OP \-\-vrf VRF name
.OP \-\-all 
.OP \-\-list
.OP \-\-summary 
.YS
.SH DESCRIPTION
This command displays static routes in the existing namespaces(VRF). 
.SH OPTIONS
.TP
\-h, \-\-help
Print help text.
.TP
\-\-vrf \ vrf
Display ports and routes present in given VRF name
.TP
.RI --all
Display ports and routes present in all VRFs
.RI --list
Display existing VRF names.
.RI --summary
Display VRF name and ports present in it.
.SH EXAMPLE
.nf
.eo
$ opx-show-vrf --vrf blue 
$ opx-show-vrf --all
$ opx-show-vrf --list
$ opx-show-vrf --summary
.ec
.fi
.SH REPORTING BUGS
To report any OPX software bugs, please refer to https://github.com/open-switch/opx-docs/wiki/Report-bugs.
.SH COPYRIGHT
Copyright \(co 2018 Dell Inc. and its subsidiaries. All Rights Reserved.
.SH SEE ALSO
opx-config-vrf(1)
