.TH opx-chassis-beacon "1" "2018-11-20" OPX "OPX utilities"
.SH NAME
opx-chassis-beacon \- Turn chassis beacon LED on or off
.SH SYNOPSIS
.SY opx-chassis-beacon
.OP "\fB\-h\fR | \fB\-\-help\fR"
.RB { on \ | \ off }
.YS
.SH DESCRIPTION
This command turns on or off the beacon LED on the chassis front panel.
.SH OPTIONS
.TP
\-h, \-\-help
Print help text.
.SH EXIT STATUS
If there is a syntax error in the given arguments, the exit status shall be 2.
.br
If the command fails to set the beacon LED, the exit status shall be 1.
.br
Otherwise, the exit status is 0.
.SH EXAMPLE
.nf
.eo
$ opx-chassis-beacon on
.ec
.fi
.SH REPORTING BUGS
To report any OPX software bugs, please refer to https://github.com/open-switch/opx-docs/wiki/Report-bugs.
.SH COPYRIGHT
Copyright \(co 2018 Dell Inc. and its subsidiaries. All Rights Reserved.
.SH SEE ALSO
opx-interface-beacon(1)
